---
title: "Code Appendix - Childhood Asthma Management Program Project - BSTA 519"
author: "Matthew Hoctor, Bryon Langford"
date: "11/30/2021"
output:
  html_document:
    number_sections: no
    theme: lumen
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readxl)
library(tidyverse)
library(ggplot2)
# library(CarletonStats)
# library(pwr)
# library(BSDA)
# library(exact2x2)
# library(car)
# library(dvmisc)
# library(emmeans)
# library(gridExtra)
# library(DescTools)
# library(DiagrammeR)
# library(nlme)
# library(doBy)
# library(geepack)
# library(rje)
```

# CAMP dataset

Import the CAMP dataset:

```{r}
camp <- read_excel("camp_2021 class project.xlsx")
```

Fill missing covariate values:

```{r}
camp <- fill(camp, c("Anypet", "Woodstove", "Dehumid", "Parent_smokes"), .direction = "down")
```

Descriptive Statistics

```{r}
# convert Visitc to numeric variable
camp$Visitc <- as.numeric(camp$Visitc)

summary(camp) # FFratio variable has 31 missing values

# Remove missing values
camp <- na.omit(camp)
```

Time Plot

```{r}
camp_mean <- camp %>%
  group_by(Trtment, Visitc) %>%
  summarise(Mean_FFratio = mean(FFratio))

camp_mean

ggplot(data = camp_mean,
       mapping = aes(x = Visitc, y = Mean_FFratio,
                     colour = factor(Trtment), group = factor(Trtment))) +
  geom_line() + geom_point() + theme(legend.position = "right") +
  labs(y = "Mean FFratio (%)", x = "Follow-up Visit (months)") +
  scale_color_manual(labels = c("Budesonide", "Nedocromil", "Placebo"), values =   c("#009E73", "#0072B2", "#CC79A7")) + 
  ggtitle("Plot of Mean Response Profiles of FFRatio by Treatment") + 
  labs(color = "Treatments")
```





